#todo
#1 AJOUTER LES TABLES
#2 AJOUTER L'INDEX DE BASE AVEC ELEMENTS DE CONNEXION
#3 SYNCHRONISER HEURE
	bash synchrniser_heure.sh
#4 AUDIO
	bash audio.sh
#5 WALLPAPER
#6 SPLASHPIC
	bash splashpic.sh
	
